### ISSUE TITLE
12.6.3制造无需信任的通道

### ISSUE THREAD

**Issue by buptsse** [tianmingyun/MasterBitcoin2CN#24]
Emma同时建立了资金和
退款交易。她签署资金交易，但不传送给任何人。Emma只将退款交易传送给Fabian，并获得他的签名。
---------
Fabian在没有收到"资金交易"的情况先, 先签名了"退款交易". 但是这个"退款交易"的资金来源是"资金交易",
Fabian怎么样确保这第一笔"退款交易"使用的资金来源是对的?
如果Emma和Fabian之间有多条通道,会不会误窜,被攻击?

**Comment by tianmingyun** [comment]
Emma和Fabian合作建立的资金交易是多签地址。Emma发起的是两笔交易：资金交易和退款交易。同样Fabian也是发起同样的两笔交易。两人各自两笔交易的地址都是这个多签地址。任何一方发起资金交易后，先不让对方签名，只是把退款交易让对方签名，确保区块高度达到后自己可以一定拿到退款。一个通道内是一个多签地址，不可能存在你说的退款错误以及通道乱窜的情况。
