### ISSUE TITLE
12.6.4 少翻译一行

### ISSUE THREAD

**Issue by yqsy** [tianmingyun/MasterBitcoin2CN#27]
翻译文章缺少的上文:

现在我们介绍这个方案的最后一个要素：一个撤销密钥，允许被欺诈的一方通过占有通道的所有余额来惩罚骗子。

这里缺少了撤销密钥的生成方式!

原文参考:
https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch12.asciidoc

The revocation key is composed of two secrets, each half generated independently by each channel participant. It is similar to a 2-of-2 multisig, but constructed using elliptic curve arithmetic, so that both parties know the revocation public key but each party knows only half the revocation secret key.

如果缺少了这一段文字,那么 "撤销密钥"的生成方式变成了由读者来推理,我起码推理了两三个小时,各种场景,全部都是有问题,有漏洞,一看原文,是你们的文章少翻译一行.  

请求你们审核修改一下,不要让别的热爱比特币的读者走了弯路,谢谢!

**Comment by tianmingyun** [comment]
非常感谢，已经修改了
