### ISSUE TITLE
京东电子书会同步更新吗

### ISSUE THREAD

**Issue by vae520283995** [tianmingyun/MasterBitcoin2CN#33]
虽然有免费版本，我还是买了一份支持

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by tianmingyun** [comment]
感谢支持。github上会周期性与英文版原文同步更新。电子书需要与出版社协商后回复您。

**Comment by Zeb-blockchain** [comment]
咨询下删除染色币这一部分的考量是怎样的呢，是比特币染色币这部分已经被历史淘汰了吗

**Comment by tianmingyun** [comment]
感谢支持。因为各种原因，目前只能在github上更新，也欢迎大家提pull request
