### ISSUE TITLE
有没有想法完善中文版的精通比特币的内容

### ISSUE THREAD

**Issue by wenzhenxiang** [tianmingyun/MasterBitcoin2CN#36]
中英版的精通比特币文档都看了，发现很多书里并未有的内容。

例如：
1.没有新的地址格式（隔离见证方面，最好有个列表显示）
2.没说清楚签名类型和应用场景
3.没有新的区块结构说明（隔离见证方面，最好有个图表示出来）
4.隔离见证板块说的不够清楚
5.比特币攻击等问题，例如自私挖矿，延展性攻击方式及原理等都没提到

其他类似的问题还有很多，这些就不只是翻译的问题了，因为英文版也没有提到，我这边可以提供技术与文档的输出。

**Comment by tianmingyun** [comment]
感谢，非常好的建议。你说的内容可以作为各章追加的扩展阅读部分，非常欢迎和我联系,微信号：yun-tianming
