### ISSUE TITLE
关于“加密货币”这一名词

### ISSUE THREAD

**Issue by qianfei11** [tianmingyun/MasterBitcoin2CN#38]
我认为“加密货币”应该修改为“密码货币”，虽然网上大部分资料也是选择将“Cryptocurrency”翻译成了“加密货币”，但在比特币中密码学的应用只涉及到了哈希函数（单向的杂凑函数）和数字签名（签名和验证两部分）两种技术，跟加密解密没有任何关系。

英文版中提到使用公钥密码并不是用来加密，而是用于生成数字签名：

> Why is asymmetric cryptography used in bitcoin? It’s not used to “encrypt” (make secret) the transactions. Rather, the useful property of asymmetric cryptography is the ability to generate digital signatures. 

同样英文中的哈希函数即`hash`仅仅表示混杂、拼凑的意思，也就是说哈希函数只是一个把字符串序列给打乱并生成没有规律的结果的一个函数，也不涉及到加密。（stackoverflow上的解释：https://stackoverflow.com/questions/326699/difference-between-hashing-a-password-and-encrypting-it）

英文版全书中包含`encrypt`的部分，除了对通讯网络的加密之外，只有BIP-38为了保护私钥涉及到了加密，所以比特币本身没有使用到任何加密技术，应该称之为“密码货币”。

**Comment by vae520283995** [comment]
虽然没有加解密,但是从某种程度上来说,哈希也相当于对数据的加密

**Comment by tianmingyun** [comment]
> 我认为“加密货币”应该修改为“密码货币”，虽然网上大部分资料也是选择将“Cryptocurrency”翻译成了“加密货币”，但在比特币中密码学的应用只涉及到了哈希函数（单向的杂凑函数）和数字签名（签名和验证两部分）两种技术，跟加密解密没有任何关系。
> 
> 英文版中提到使用公钥密码并不是用来加密，而是用于生成数字签名：
> 
> > Why is asymmetric cryptography used in bitcoin? It’s not used to “encrypt” (make secret) the transactions. Rather, the useful property of asymmetric cryptography is the ability to generate digital signatures.
> 
> 同样英文中的哈希函数即`hash`仅仅表示混杂、拼凑的意思，也就是说哈希函数只是一个把字符串序列给打乱并生成没有规律的结果的一个函数，也不涉及到加密。（stackoverflow上的解释：[https://stackoverflow.com/questions/326699/difference-between-hashing-a-password-and-encrypting-it）](https://stackoverflow.com/questions/326699/difference-between-hashing-a-password-and-encrypting-it%EF%BC%89)
> 
> 英文版全书中包含`encrypt`的部分，除了对通讯网络的加密之外，只有BIP-38为了保护私钥涉及到了加密，所以比特币本身没有使用到任何加密技术，应该称之为“密码货币”。

这位朋友说的有道理。严格意义上，比特币不是加密货币。一般意义的”加密数字货币“可能更多是方便对行业外的人解释。感谢建议。已经修改。
