### ISSUE TITLE
请问矿工或其它人会窃取用户的解锁脚本吗？

### ISSUE THREAD

**Issue by qigezuishuaide** [tianmingyun/MasterBitcoin2CN#39]
如果A要转给B比特币，A提供了自己的解锁脚本。C用解锁脚本验证通过了，就把A->B这个交易修改成了A->C，并打包成功。反正解锁脚本只会有A的信息，是不会有B的任何信息的，我造了假也没人知道。
我是哪里在理解的时候出了问题，谢谢

**Comment by tianmingyun** [comment]
A转给B，其中锁定脚本包括了B的公钥，只有B的私钥才可以解锁，不理解你说的C如何解锁？如何造假？
