### ISSUE TITLE
简书的图好像都挂了

### ISSUE THREAD

**Issue by yuyang0** [tianmingyun/MasterBitcoin2CN#53]
jianshu.io的图全是403

**Comment by tianmingyun** [comment]
github上的图全部替换掉简书的图床，是英文原版原图，git自己图床，有时国内不稳定，翻一下或者多试几次发自我的华为手机-------- 原始邮件 --------发件人： Yu Yang ***@***.***>日期： 2022年6月10日周五 21:31收件人： tianmingyun/MasterBitcoin2CN ***@***.***>抄送： Subscribed ***@***.***>主    题： [tianmingyun/MasterBitcoin2CN] 简书的图好像都挂了 (Issue #53)

jianshu.io的图全是403

**Comment by yuyang0** [comment]
你这个的原因大概率是简书根据http 的referer 把所有的图片请求都ban掉了

**Comment by yuyang0** [comment]
github上能看，gitbook的图是都挂了的
