### ISSUE TITLE
glossary 哈希锁里面似乎有个错别字

### ISSUE THREAD

**Issue by chenhuaying** [tianmingyun/MasterBitcoin2CN#8]
哈希锁:

哈希锁是限制一个输出花费的限制对象，其作用一直持续到指定数据片段公开透露。哈希锁有一个有用的属性，那就是一旦任意一个哈希锁被公开打开，其他任何安全使用相同密钥的哈希锁也可以被打开。这使得可能创建多个被同意哈希锁限制的输出，这些支出将在同一时间被花费。

"同意哈希锁限制的输出" 这个里面的同意是不是应该是“同一”？

**Comment by lingfengchencn** [comment]
+1

**Comment by tianmingyun** [comment]
谢谢，已修改
